fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: OAuthBundle:Access:login }

oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
