parameters:
#    synchronize.example.class: EducacityREST\SynchronizeBundle\Example

services:
#    synchronize.example:
#        class: %synchronize.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
