EducacityREST\UserBundle\Entity\AppUser:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        email:
            expose: true
        registeredDate:
            exposed: true